[package]
name = "dmd_analyzer_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
lru = "0.12.4"
polars = "0.41.3"
tokenizers = "0.20.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8"
regex = "1"